name: 'The name of your action here'
description: 'Provide a description here'
author: 'Your name or organization here'

# Define your inputs here.
inputs:
  release-tag:
    description: 'A valid tag indicating a new release'
    required: true
  github-token:
    description: 'Github token to fetch data from Github API'
    required: true

runs:
  using: node20
  main: dist/index.js
